### ISSUE TITLE
Add ufw / fail2ban box security

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/open-corroborator-deploy#10]
Probably via ansible. Maybe we can reuse some of [caislean](https://github.com/equalitie/caislean)?

**Comment by ggaughan** [comment]
Added basic ufw

**Comment by ggaughan** [comment]
Will leave further security (beyond basic firewall settings) out of the default ansible scripts since anything further will need to be customised depending on the instance/ops available.
