### ISSUE TITLE
Install ffmpeg if video thumbnails are needed again

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/open-corroborator-deploy#5]
This is no longer included in ubuntu 14.0, so will need to be built from source or installed from a ppa.

**Comment by ggaughan** [comment]
This is now built from sources (ffmpeg + various codecs). Adds an extra 30 mins (+2G) or so to the initial deployment (and is dependent  on the external sources being available at initial deploy time). Build can be turned off via `ffmpeg:no` (probably coupled with setting `VIDEO_THUMBNAILING=False` in the app to avoid using it).
